// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	article "EnjoyBlog/app/admin/api/internal/handler/article"
	user "EnjoyBlog/app/admin/api/internal/handler/user"
	"EnjoyBlog/app/admin/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/info",
				Handler: user.GetUserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: user.GetUserListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/api/admin/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/info",
				Handler: article.GetArticleInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/adminLogin",
				Handler: article.AdminLoginHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/api/admin/article"),
	)
}
