// Code generated by goctl. DO NOT EDIT.
package types

type UserInfoReq struct {
	UserId string `form:"userId"`
}

type UserInfoResp struct {
	Id          int64  `json:"id"`
	IsAdmin     int32  `json:"isAdmin"`
	UserId      string `json:"userId"`
	Username    string `json:"username"`
	Email       string `json:"email"`
	Phone       string `json:"phone"`
	Password    string `json:"-"`
	Avatar      string `json:"avatar"`
	NickName    string `json:"nickName"`
	Description string `json:"description"`
	CreateTime  string `json:"createTime"`
	UpdateTime  string `json:"updateTime"`
}

type UserListReq struct {
	Page     int    `form:"page"`     // 页面
	PageSize int    `form:"pageSize"` // 页面大小
	Desc     int    `form:"desc"`     // 1降序, 0默认升序
	OrderKey string `form:"orderKey"` // 排序关键字
}

type UserListResp struct {
	UserList []UserInfoResp `json:"userList"`
}

type AdminLoginReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type AdminLoginResp struct {
	Id           int64  `json:"id"`
	UserId       string `json:"userId"`
	Username     string `json:"username"`
	Email        string `json:"email"`
	Phone        string `json:"phone"`
	Password     string `json:"-"`
	Avatar       string `json:"avatar"`
	NickName     string `json:"nickName"`
	Description  string `json:"description"`
	CreateTime   string `json:"createTime"`
	UpdateTime   string `json:"updateTime"`
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
}

type ArticleInfoReq struct {
	ArticleId string `json:"articleId"`
}

type ArticleInfoResp struct {
}
