// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"EnjoyBlog/app/comment/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: GetCommentListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/add",
				Handler: AddCommentHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/support",
				Handler: supportHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/comment"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodDelete,
				Path:    "/delete",
				Handler: DeleteCommentHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/api/comment"),
	)
}
