// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"EnjoyBlog/app/user/rpc/internal/logic"
	"EnjoyBlog/app/user/rpc/internal/svc"
	"EnjoyBlog/app/user/rpc/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) GetUserInfo(ctx context.Context, in *user.UserInfoReq) (*user.UserInfoResp, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}

func (s *UserServer) GetUserList(ctx context.Context, in *user.UserListReq) (*user.UserListResp, error) {
	l := logic.NewGetUserListLogic(ctx, s.svcCtx)
	return l.GetUserList(in)
}

func (s *UserServer) GetAll(in *user.UserListReq, stream user.User_GetAllServer) error {
	l := logic.NewGetAllLogic(stream.Context(), s.svcCtx)
	return l.GetAll(in, stream)
}
