// Code generated by goctl. DO NOT EDIT.
package types

type ArticleInfoReq struct {
	ArticleId string `form:"articleId"`
}

type SearchArticleListReq struct {
	ArticleListReq
	SearchKey string `form:"searchKey"`
}

type ArticleListByGroupIdReq struct {
	ArticleListReq
	ArticleGroupId string `form:"articleGroupId"`
}

type ArticleListByLabelReq struct {
	ArticleListReq
	Label string `form:"label"` // 标签
}

type ArticleListReq struct {
	Page     int    `form:"page"`     // 页面
	PageSize int    `form:"pageSize"` // 页面大小
	Desc     int    `form:"desc"`     // 1降序, 0默认升序
	OrderKey string `form:"orderKey"` // 排序关键字
	UserId   string `form:"userId"`
}

type ArticleListResp struct {
	ArticleList []ArticleInfo `json:"articleList"`
}

type AddArticleInfoReq struct {
	ArticleTitle   string `json:"articleTitle"`
	ArticleCttHtml string `json:"articleCttHtml"`
	ArticleCttMd   string `json:"articleCttMd"`
	ArticleGroupId string `json:"articleGroupId"`
	Avatar         string `json:"avatar"`
	Label          string `json:"label"`
	IsTop          int    `json:"isTop"`
	IsPub          int    `json:"isPub"`
}

type UpdateArticleInfoReq struct {
	ArticleId      string `json:"articleId"`
	ArticleTitle   string `json:"articleTitle"`
	ArticleCttHtml string `json:"articleCttHtml"`
	ArticleCttMd   string `json:"articleCttMd"`
	Avatar         string `json:"avatar"`
	Label          string `json:"label"`
	IsTop          int    `json:"isTop"`
	IsPub          int    `json:"isPub"`
}

type ArticleInfo struct {
	Id             int    `json:"id"`
	UserId         string `json:"userId"`
	ArticleId      string `json:"articleId"`
	ArticleTitle   string `json:"articleTitle"`
	ArticleCttHead string `json:"articleCttHead"` // 文章内容开头
	Avatar         string `json:"avatar"`
	Label          string `json:"label"`
	IsTop          int    `json:"isTop"`
	IsPub          int    `json:"isPub"`
	CommentTotal   int    `json:"commentTotal"`
	SupportTotal   int    `json:"supportTotal"`
	CreateTime     string `json:"createTime"`
	UpdateTime     string `json:"updateTime"`
}

type ArticlePublicInfo struct {
	UserId         int    `json:"userId"`
	ArticleId      int    `json:"articleId"`
	ArticleTitle   string `json:"articleTitle"`
	ArticleCttHead string `json:"article_ctt_head"` // 文章内容开头
	Avatar         string `json:"avatar"`
	Label          string `json:"label"`
	CommentTotal   int    `json:"commentTotal"`
	SupportTotal   int    `json:"supportTotal"`
	CreateTime     string `json:"createTime"`
}

type ArticleInfoWithContent struct {
	ArticleInfo
	ArticleCttHtml string `json:"articleCttHtml"`
	ArticleCttMd   string `json:"articleCttMd"`
}

type DeleteArticleReq struct {
	ArticleId string `json:"articleId"`
}
