// Code generated by goctl. DO NOT EDIT.
package types

type ArticleInfoReq struct {
	ArticleId string `form:"articleId"`
}

type SearchArticleListReq struct {
	ArticleListReq
	SearchKey string `form:"searchKey"`
}

type ArticleListByGroupIdReq struct {
	ArticleListReq
	ArticleGroupId string `form:"articleGroupId"`
}

type ArticleListByLabelReq struct {
	ArticleListReq
	Label string `form:"label"` // 标签
}

type ArticleListReq struct {
	Page     int    `form:"page"`     // 页面
	PageSize int    `form:"pageSize"` // 页面大小
	Desc     int    `form:"desc"`     // 1降序, 0默认升序
	OrderKey string `form:"orderKey"` // 排序关键字
	UserId   string `form:"userId"`
}

type ArticleListResp struct {
	ArticleList []ArticleInfo `json:"articleList"`
}

type EditArticleInfoReq struct {
	ArticleTitle   string `json:"articleTitle"`
	ArticleContent string `json:"articleContent"`
	Avatar         string `json:"avatar"`
	Label          string `json:"label"`
	IsTop          int    `json:"isTop"`
	IsPub          int    `json:"isPub"`
}

type ArticleInfo struct {
	Id           int    `json:"id"`
	UserId       string `json:"userId"`
	ArticleId    string `json:"articleId"`
	ArticleTitle string `json:"articleTitle"`
	Avatar       string `json:"avatar"`
	Label        string `json:"label"`
	IsTop        int    `json:"isTop"`
	IsPub        int    `json:"isPub"`
	CommentTotal int    `json:"commentTotal"`
	SupportTotal int    `json:"supportTotal"`
	CreateTime   string `json:"createTime"`
	UpdateTime   string `json:"updateTime"`
}

type ArticlePublicInfo struct {
	UserId       int    `json:"userId"`
	ArticleId    int    `json:"articleId"`
	ArticleTitle string `json:"articleTitle"`
	Avatar       string `json:"avatar"`
	Label        string `json:"label"`
	CommentTotal int    `json:"commentTotal"`
	SupportTotal int    `json:"supportTotal"`
	CreateTime   string `json:"createTime"`
}

type ArticleInfoWithContent struct {
	ArticleInfo
	ArticleContent string `json:"articleContent"`
}

type DeleteArticleReq struct {
	ArticleId string `json:"articleId"`
}
