// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"EnjoyBlog/app/article/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: GetArticleListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/listBylabel",
				Handler: GetArticleListByLabelHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/listByGroupId",
				Handler: GetArticleListByGroupIdHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/search",
				Handler: GetArticleListBySearchHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/info",
				Handler: GetArticleInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/support",
				Handler: SupportHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/article"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/add",
				Handler: AddArticleHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/update",
				Handler: UpdateArticleHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/delete",
				Handler: DeleteArticleHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/api/article"),
	)
}
