// Code generated by goctl. DO NOT EDIT.
package types

type CommentListReq struct {
	ArticleId string `json:"articleId"`
}

type CommentListResp struct {
	CommentList []CommentInfo `json:"commentList"`
}

type CommentInfo struct {
	Id               int64  `json:"id"`               // 自增id
	CommentId        string `json:"commentId"`        // 评论id
	CommentContent   string `json:"commentContent"`   // 评论内容
	CommentatorName  string `json:"commentatorName"`  // 发表评论者
	CommentatorEmail string `json:"commentatorEmail"` // 发表评论者邮箱
	SupportTotal     int64  `json:"supportTotal"`     // 点赞总数
	ArticleId        string `json:"articleId"`        // 文章id
	ParentId         string `json:"parentId"`         // 父评论id, 0默认顶层
	IsPub            int64  `json:"isPub"`            // 评论是否仅最多三方可看, 1默认公开
	CreateTime       string `json:"createTime"`
}

type AddCommentReq struct {
	CommentContent   string `json:"commentContent"`   // 评论内容
	CommentatorName  string `json:"commentatorName"`  // 发表评论者
	CommentatorEmail string `json:"commentatorEmail"` // 发表评论者邮箱
	ArticleId        string `json:"articleId"`        // 文章id
	ParentId         string `json:"parentId"`         // 父评论id, 0默认顶层
	IsPub            int64  `json:"isPub"`            // 评论是否仅最多三方可看, 1默认公开
}

type DeleteCommentReq struct {
	ArticleId string `json:"articleId"`
	CommentId string `json:"commentId"`
}

type SupportReq struct {
	CommentId string `json:"commentId"`
}
